projects:
  mimesweep:
    schemaPath: src/graphql/schema.json
    includes:
      - highScore
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
